[package]
name = "file-store"
version = "0.1.0"
authors.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
